### ISSUE TITLE
Attempting to open physics/collision SMD's causes a crash

### ISSUE THREAD

**Issue by roket333** [xNWP/Cinema-4D-Source-Tools#2]
tried to open the physics/collision model for the sniper rifle i sent you in the last issue and it caused a crash
also tried with the Rescue Ranger, Loch-n-Load and Eyelander, also causing crashes

**Comment by xNWP** [comment]
Hey roket, I became aware of this shortly after fixing the last bug you sent, it was also related to the new material engine (which probably has some more bugs to find). This is fixed as of 0.42-alpha, thanks for reporting these again !
