### ISSUE TITLE
Crash on opening in C4D R19.053

### ISSUE THREAD

**Issue by ApexJohn** [xNWP/Cinema-4D-Source-Tools#3]
It just keeps saying the plugin was installed successfully when I boot it every time, after that it just crashes C4D with "A critical error occured" when I click on it in plugins.

**Comment by MisterAlphito** [comment]
Actually, im using R19.053 and I don't have any problem with the plugin

**Comment by xNWP** [comment]
Hi Apex, sorry for the late reply, I tested myself with R19.053 with no issues whatsoever. If you'd like you may add me on Discord and I can explore the issue further with you over screenshare/teamviewer.

Discord: xNWP#1337

**Comment by c0deisme** [comment]
i'm having the same issue..

**Comment by xNWP** [comment]
Hi c0deisme could you specify the cinema 4d version you are using as well as operating system. Also try removing any other plugins and see if they might be conflicting

**Comment by c0deisme** [comment]
same c4d version, no other plugins and windows 10 april update

**Comment by xNWP** [comment]
Hmmm, I'm at work right now but will test when I get home (approx. 3 hours)

**Comment by c0deisme** [comment]
i just tried using it in a fresh installed version of c4d r19, no luck either

**Comment by c0deisme** [comment]
i finally got it to work, doesnt work in the install directory, has to be in the preference dir..
and that now only works after a re-download

**Comment by xNWP** [comment]
Hi c0deisme, I tested last night and had no issues with the install being under the Cinema 4D root directory (and not the appdata directory). It could possibly be an issue with illegal characters in your C4D root path, i.e. not alphanumeric ascii characters (a-z, A-Z, 0-9). If you'd like to explore the issue further feel free to contact me on discord (xNWP#1337).
