### ISSUE TITLE
Build\x64_Release\*.cdl64 no found

### ISSUE THREAD

**Issue by chory** [xNWP/Cinema-4D-Source-Tools#4]
Where is this file?
Thanks

**Comment by chory** [comment]
Upss, nope.
I need a c++ compiler  :flushed:

**Comment by xNWP** [comment]
Hello, sorry about the very late reply. The plugin requires VS2013 (or the relevant msbuild version) for compilation.

**Comment by xNWP** [comment]
Update: The version you would have been trying to build with has quite a bunch of issues and weird framework mismatches, I've fixed all of this and added a how_to_build.txt in the latest commit. I'll be closing this issue now, if you have any further issues feel free to reopen it or make a new issue.

**Comment by chory** [comment]
I will to install VS2013 in other computer.
