### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by ChangeOtaku** [xNWP/Cinema-4D-Source-Tools#5]
Hello,

im a C4D user and i already have my playermodel... but i dont understood how to use your plugin.
do you have some video or something like that that explains it?

**Comment by xNWP** [comment]
Hi ChangeOtaku,

assuming the plugin has been installed without issue (you can check by looking for its entry in the plugins menu), you can import the model by simply opening it (assuming it's an SMD/QC file) like you would any other file.

**Comment by ChangeOtaku** [comment]
Ok,
According to this...
Some issue happened xD
But its ok :/
I already found a program that converts into SDM.
And i was waching a tutorial to create my playermodel addon for GMod and its a bit complicated to me xD
I will search for someone who uderstand about that

**Comment by xNWP** [comment]
Closing the issue, if you need any more help feel free to open a new issue or reopen this one.
