### ISSUE TITLE
C4D LITE

### ISSUE THREAD

**Issue by hex50core** [xNWP/Cinema-4D-Source-Tools#8]
Please tell me how to use this in c4d r18 lite ADOBE AFTER EFFECTS

**Comment by xNWP** [comment]
Currently we are not targeting special versions of Cinema 4D (such as lite). I haven't tested it myself as that is not the version that I own. Geometry (so SMD import) should work fine in AE as once the geometry is built by the plugin it is treated like any other mesh. Using VTF textures however has not been tested with AE's interop. with Cinema 4D. You can give it a shot but I cannot guarantee that it will work.
